### ISSUE TITLE
ValueError: mutable default <class 'stopes.core.stopes_module.Requirements'> for field requirements is not allowed: use 

### ISSUE THREAD

**Issue by dtometzki** [facebookresearch/large_concept_model#8]
Hello together,

merry christmas. I get the following error when execute: hat is wrong here

what is wrong here ?

```
/large_concept_model/scripts$ python3.11 prepare_wikipedia.py ./wiki_data
Traceback (most recent call last):
  File "/root/large_concept_model/scripts/prepare_wikipedia.py", line 13, in <module>
    from stopes.modules.preprocess.sonar_text_embedding import (
  File "/opt/conda/lib/python3.11/site-packages/stopes/modules/preprocess/__init__.py", line 7, in <module>
    from .line_processor import LineProcessorCallback as LineProcessorCallback
  File "/opt/conda/lib/python3.11/site-packages/stopes/modules/preprocess/line_processor.py", line 62, in <module>
    @dataclass
     ^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 1232, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 1222, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'stopes.core.stopes_module.Requirements'> for field requirements is not allowed: use default_factory
```

Best regards
Damian

**Comment by dtometzki** [comment]
Hello the following change resolved my issue: 

```
diff --git a/stopes/modules/preprocess/line_processor.py b/stopes/modules/preprocess/line_processor.py
index d6dedc3..7768203 100644
--- a/stopes/modules/preprocess/line_processor.py
+++ b/stopes/modules/preprocess/line_processor.py
@@ -9,7 +9,7 @@ import logging
 import typing as tp
 from abc import abstractmethod
 from contextlib import AbstractContextManager
-from dataclasses import dataclass
+from dataclasses import dataclass, field
 from pathlib import Path
 
 import hydra
@@ -69,13 +69,13 @@ class LineProcessorConfig:
     # if only hydra allowed, the right type would be tp.Union[str, tp.List[str]]
     shards: tp.Any = MISSING
     buffer_size: int = 10_000
-    requirements: Requirements = Requirements(
-        nodes=1,
-        tasks_per_node=1,
-        gpus_per_node=0,
-        cpus_per_task=4,
-        timeout_min=120,
-    )
+    requirements: Requirements = field(default_factory=lambda: Requirements(
+       nodes=1,
+       tasks_per_node=1,
+       gpus_per_node=0,
+       cpus_per_task=4,
+       timeout_min=120
+    ))
     custom_name: str = ""
```

**Comment by Charley-xiao** [comment]
The changes proposed by @dtometzki worked for me. However, I'm encountering another issue:

```bash
Traceback (most recent call last):
  File "/home/xqw/miniconda3/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/tqdm/contrib/logging.py", line 93, in logging_redirect_tqdm
    yield
  File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/stopes/core/launcher.py", line 324, in schedule
    result = await self._schedule_array(module, value_array)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/stopes/core/launcher.py", line 540, in _schedule_array
    raise ArrayTaskError(
stopes.core.launcher.ArrayTaskError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/patchranking/large_concept_model/scripts/prepare_wikipedia.py", line 103, in <module>
    fire.Fire(run)
  File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/patchranking/large_concept_model/scripts/prepare_wikipedia.py", line 99, in run
    asyncio.run(launcher.schedule(stopes_module))
  File "/home/xqw/miniconda3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/xqw/miniconda3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xqw/miniconda3/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/stopes/core/launcher.py", line 319, in schedule
    with logging_redirect_tqdm():
  File "/home/xqw/miniconda3/lib/python3.12/contextlib.py", line 191, in __exit__
    exc.__traceback__ = traceback
    ^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field '__traceback__'
```

I'm not sure if this is related to the changes I just made, or it's just another issue regarding how the developers handle dataclasses.

**Comment by elbayadm** [comment]
> The changes proposed by @dtometzki worked for me. However, I'm encountering another issue:
> 
> ```shell
> Traceback (most recent call last):
>   File "/home/xqw/miniconda3/lib/python3.12/contextlib.py", line 158, in __exit__
>     self.gen.throw(value)
>   File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/tqdm/contrib/logging.py", line 93, in logging_redirect_tqdm
>     yield
>   File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/stopes/core/launcher.py", line 324, in schedule
>     result = await self._schedule_array(module, value_array)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/stopes/core/launcher.py", line 540, in _schedule_array
>     raise ArrayTaskError(
> stopes.core.launcher.ArrayTaskError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/data/patchranking/large_concept_model/scripts/prepare_wikipedia.py", line 103, in <module>
>     fire.Fire(run)
>   File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/fire/core.py", line 135, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/fire/core.py", line 468, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>                                 ^^^^^^^^^^^^^^^^^^^^
>   File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>                 ^^^^^^^^^^^^^^^^^^^^^^
>   File "/data/patchranking/large_concept_model/scripts/prepare_wikipedia.py", line 99, in run
>     asyncio.run(launcher.schedule(stopes_module))
>   File "/home/xqw/miniconda3/lib/python3.12/asyncio/runners.py", line 194, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/home/xqw/miniconda3/lib/python3.12/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/xqw/miniconda3/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/data/patchranking/large_concept_model/.venv/lib/python3.12/site-packages/stopes/core/launcher.py", line 319, in schedule
>     with logging_redirect_tqdm():
>   File "/home/xqw/miniconda3/lib/python3.12/contextlib.py", line 191, in __exit__
>     exc.__traceback__ = traceback
>     ^^^^^^^^^^^^^^^^^
>   File "<string>", line 4, in __setattr__
> dataclasses.FrozenInstanceError: cannot assign to field '__traceback__'
> ```
> 
> I'm not sure if this is related to the changes I just made, or it's just another issue regarding how the developers handle dataclasses.

Hi, @Charley-xiao! 
I haven't encountered this issue before. Can you share a reproducing example? 
is this simply running `python prepare_wikipedia.py ./wiki_data`? I see also a mix of miniconda and venv in the trace, is this intentional?

**Comment by Charley-xiao** [comment]
Hi, @elbayadm. Thanks for replying.

Yes, I ran `python scripts/prepare_wikipedia.py` in a Conda environment after following the installation instructions using `uv`, as outlined in README.md. Then, I encountered the issue mentioned by @dtometzki and tried his solution, which worked but then yielded another problem as in my first comment. Now that you’ve mentioned the possibility of mixing Miniconda and venv, I realize that could be causing the issue.

**Comment by Charley-xiao** [comment]
> @Charley-xiao give it a try after pulling the latest changes (to fix the default_factory issue) and running
> 
> ```
> conda deactivate
> source .venv/bin/activate
> ```

It worked! Thank you so much, @elbayadm. The mix of the environments is indeed the problem.

**Comment by StephenJHardy** [comment]
> Hi, @dtometzki! Indeed, IIUC python > 3.11 throws an error with mutable defaults and requires the use of `default_factory`. In #11 I made changes to a few dataclasses to use `default_factory`

Hi, I still have the same error as reported above - this is from a checkout of main including #11 - python 3.12.3 on ubuntu. 

`Traceback (most recent call last):
  File "/home/stephen/checkouts/large_concept_model/scripts/prepare_wikipedia.py", line 13, in <module>
    from stopes.modules.preprocess.sonar_text_embedding import (
  File "/home/stephen/venv_fairseq/lib/python3.12/site-packages/stopes/modules/preprocess/__init__.py", line 7, in <module>
    from .line_processor import LineProcessorCallback as LineProcessorCallback
  File "/home/stephen/venv_fairseq/lib/python3.12/site-packages/stopes/modules/preprocess/line_processor.py", line 62, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.12/dataclasses.py", line 1268, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.12/dataclasses.py", line 1258, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/dataclasses.py", line 994, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/dataclasses.py", line 852, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'stopes.core.stopes_module.Requirements'> for field requirements is not allowed: use default_factory
`

**Comment by dtometzki** [comment]
Hello @elbayadm 

the changes are missing in packages stopes. 

/opt/conda/lib/python3.11/site-packages/stopes/modules/preprocess/line_processor.py. 

I got the same erroro again
```
root@C.15463699:~/large_concept_model/examples/evaluation$ python prepare_evaluation_data.py ./wiki_dat
Traceback (most recent call last):
  File "/root/large_concept_model/examples/evaluation/prepare_evaluation_data.py", line 27, in <module>
    from stopes.modules.preprocess.sonar_text_embedding import (
  File "/opt/conda/lib/python3.11/site-packages/stopes/modules/preprocess/__init__.py", line 7, in <module>
    from .line_processor import LineProcessorCallback as LineProcessorCallback
  File "/opt/conda/lib/python3.11/site-packages/stopes/modules/preprocess/line_processor.py", line 62, in <module>
    @dataclass
     ^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 1232, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 1222, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'stopes.core.stopes_module.Requirements'> for field requirements is not allowed: use default_factory
```
Damian

**Comment by elbayadm** [comment]
@dtometzki  I re-opened this issue. In #11, I only fixed the training errors caused by `default_factory` in the lcm package. We need to also fix this issue in stopes.
