### ISSUE TITLE
Provide a short, descriptive title of the issue, such as "Dataset partition error due to missing 'split' column".

### ISSUE THREAD

**Issue by aditya6396** [facebookresearch/large_concept_model#9]
###my code 

[2024-12-27 17:32:58,897][lcm.train.metrics][WARNING] - wandb not found. Please install it with `pip install wandb`.                                                                                               
[2024-12-27 17:32:58,920][lcm.train.trainer][INFO] - Setting up AdamW optimizer with betas=[0.9, 0.95], base lr=0.0004 and weight decay=0.1 and use_fp32=True                                                      
[2024-12-27 17:32:58,920][fairseq2.optim.dynamic_loss_scaler][INFO] - The scale window is set to 16384.                                                                                                            
[2024-12-27 17:32:58,920][lcm.train.trainer][INFO] - Initializing DynamicLossScaler with init_scale=32768.0                                                                                                        
[2024-12-27 17:32:58,921][lcm.train.trainer][INFO] - Running training on 1 device(s).                                                                                                                              
[2024-12-27 17:32:58,921][lcm.train.trainer][INFO] - R0 - waiting for all ranks to prepare a data iterator!                                                                                                        
  0%|                                                                                                                                                                                        | 0/1 [00:00<?, ?it/s]NCCL version 2.21.5+cuda12.4
[2024-12-27 17:32:59,035][lcm.datasets.base][INFO] - R0 self._pipeline is None, building...                                                                                                                        
[2024-12-27 17:32:59,036][lcm.datasets.dataloading][INFO] - getting exception during filters examination : Partition filters (split == "train") is set but dataset has NO partition columns                        
[2024-12-27 17:32:59,036][lcm.datasets.dataloading][INFO] - Following columns will be loaded: ['text_sentences', 'text_sentences_sonar_emb']                                                                       
[2024-12-27 17:32:59,037][lcm.train.trainer][WARNING] - R0 checkpoint_and_raise - error=No match for FieldRef.Name(split) in id: string                                                                            
url: string
title: string
text: string
text_sentences: list<element: string>
text_sentences_sonar_emb: list<element: fixed_size_list<element: float>[1024]>
  0%|                                                                                                                                                                                        | 0/1 [00:00<?, ?it/s]No match for FieldRef.Name(split) in id: string
url: string
title: string
text: string
text_sentences: list<element: string>

i running it in my local 

with this command 
CUDA_VISIBLE_DEVICES=0 uv run torchrun --standalone --nnodes=1 --nproc-per-node=1     -m lcm.train launcher=standalone     +pretrain=mse     ++trainer.data_loading_config.max_tokens=1000     ++trainer.output_dir="checkpoints/mse_lcm"     +trainer.use_submitit=false

my datacard file is

## FIXME
name: "pretraining_data"
parquet_path:
  #s3: "s3://dl.fbaipublicfiles.com/LCM/rocstories"
  #s3: "/large_experiments/lcm/data/sonarized/rocstories"
  local: "/home/lcm/large_concept_model/output/"
source_column: "text_sentences_sonar_emb"
source_text_column: "text_sentences"
 partition columns:

'split :(train, validation)

**Comment by hasanyazarr** [comment]
Hi, I encountered this error too and I solved it by adding this code:

```py
import pandas as pd

dataset_path = "/content/large_concept_model/sample_data/0_a25e918a7789ecfa_0_0.parquet" # dataset path 

df = pd.read_parquet(dataset_path) # load dataset in pandas df

df['split'] = 'train' # adding 'split' column to dataset because of the missing split column

df.to_parquet(dataset_path) # convert dataset to parquest again
```

Actually, I am not sure about the how correct or valid this solution is but it worked for me.

**Comment by elbayadm** [comment]
Hi, @aditya6396!
We assume our datasets are partitioned into splits i.e, the dataset will look like
```
.
├── split=train
│   └── 0_24f91e3aa8bb4655_0_0.parquet
└── split=validation
    └── 0_24f91e3aa8bb4732_0_0.parquet
```
That's why the training recipe refers to data spits as:
```yaml
training_data:
  - name: "pretraining_data=train"   # loads the partition split=train
    source_suffix_text: "End of text."

validation_data:
  - name: "pretraining_data=validation" # loads the partition split=validation
    source_suffix_text: "End of text."
```
If that's not the case you can change the recipe to something like

```yaml
training_data:
  - name: "pretraining_data"
    source_suffix_text: "End of text."

validation_data:
  - name: "some_other_separate_validation_data"
    source_suffix_text: "End of text."
```

**Comment by aditya6396** [comment]
thank you for replay but arrange my data according to you done it last replay but in the time of the nomalizing the datasets but its giving me this error mentation it below 
i m using this command 
uv run python scripts/fit_embedding_normalizer.py --ds pretraining_data:1 --save_path "my local path" --max_nb_samples 1000000
my dataymal file 

# FIXME
name: "pretraining_data"
parquet_path:
  s3: "wiki_data"
source_column: "text_sentences_sonar_emb"
source_text_column: "text_sentences"
# partition columns:


###this coming due to the python version i using the python 3.10 should i used the python 3.11##

Traceback (most recent call last):
  File "/home/cpatwadityasharma/large_concept_model/scripts/fit_embedding_normalizer.py", line 101, in <module>
    main(args.ds, args.save_path, args.max_nb_samples)
  File "/home/cpatwadityasharma/large_concept_model/scripts/fit_embedding_normalizer.py", line 79, in main
    embs = sample_sentences_from_mixed_sources(
  File "/home/cpatwadityasharma/large_concept_model/scripts/fit_embedding_normalizer.py", line 52, in sample_sentences_from_mixed_sources
    vecs = pyarrow_fixed_size_array_to_numpy(pc.list_flatten(batch[column]))[
  File "/home/cpatwadityasharma/large_concept_model/.venv/lib/python3.10/site-packages/stopes/utils/arrow_utils.py", line 152, in pyarrow_fixed_size_array_to_numpy
    assert cc.type.list_size is not None
AttributeError: 'pyarrow.lib.ListType' object has no attribute 'list_size'
0it [00:01, ?it/s]

**Comment by artemru** [comment]
> thank you for replay but arrange my data according to you done it last replay but in the time of the nomalizing the datasets but its giving me this error mentation it below i m using this command uv run python scripts/fit_embedding_normalizer.py --ds pretraining_data:1 --save_path "my local path" --max_nb_samples 1000000 my dataymal file
> 
> # FIXME
> name: "pretraining_data" parquet_path: s3: "wiki_data" source_column: "text_sentences_sonar_emb" source_text_column: "text_sentences"
> 
> # partition columns:
> ###this coming due to the python version i using the python 3.10 should i used the python 3.11##
> 
> Traceback (most recent call last): File "/home/cpatwadityasharma/large_concept_model/scripts/fit_embedding_normalizer.py", line 101, in main(args.ds, args.save_path, args.max_nb_samples) File "/home/cpatwadityasharma/large_concept_model/scripts/fit_embedding_normalizer.py", line 79, in main embs = sample_sentences_from_mixed_sources( File "/home/cpatwadityasharma/large_concept_model/scripts/fit_embedding_normalizer.py", line 52, in sample_sentences_from_mixed_sources vecs = pyarrow_fixed_size_array_to_numpy(pc.list_flatten(batch[column]))[ File "/home/cpatwadityasharma/large_concept_model/.venv/lib/python3.10/site-packages/stopes/utils/arrow_utils.py", line 152, in pyarrow_fixed_size_array_to_numpy assert cc.type.list_size is not None AttributeError: 'pyarrow.lib.ListType' object has no attribute 'list_size' 0it [00:01, ?it/s]

Can you show the schema of your dataset ? I suspect that embeddings are stored as a simple pyarrow.List and not as  FixedSizeList(dim=1024). If this's an issue. it typically happens if you do read/write operations with pandas which does not support correctly this round-trip.

**Comment by aditya6396** [comment]
this ymal.file 

name: "pretraining_data"
parquet_path:
  s3: "wiki_data"  
  # train: "/home/cpatwadityasharma/lcm/large_concept_model/wiki_data/split/train"
  # validation: "/home/cpatwadityasharma/lcm/large_concept_model/wiki_data/split/validation"
source_column: "text_sentences_sonar_emb"
source_text_column: "text_sentences

my data saved after the download

wiki_datafolder 

which have the file 0_b0ddbee86cdf7d47_0_0.parquet


after it used the command this 

the command you give 
python scripts/fit_embedding_normalizer.py --ds dataset1:4 dataset2:1 dataset3:10 --save_path "path/to/new/normalizer.pt" --max_nb_samples 1000000

my dataset schema 
import pyarrow as pa

schema = pa.schema([
    ("id", pa.int64()),
    ("url", pa.string()),
    ("text_sentences_sonar_emb", pa.list_(pa.list_(pa.float32()))),
])

i making the normal.pt file will be according to my ymal file 

uv run python scripts/fit_embedding_normalizer.py --ds pretraining_data:1 --save_path "/home/cpatwadityasharma/lcm/large_concept_model/output/normalizer.pt" --max_nb_samples 1000000

the error i mentation in above 

i also folow these step 
training_data:
  - name: "pretraining_data"
    source_suffix_text: "End of text."

validation_data:
  - name: "some_other_separate_validation_data"
    source_suffix_text: "End of text."



provided me solution  how to done it
